name: CI Pipeline
run-name: ${{ github.actor }} is running tests 🚀
on:
  push:
    branches:
      - 'main'

env:
  TOKEN: ${{ secrets.GH_PAT }}
  PAYSTACK_KEY: {{ secrets.PAYSTACK_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - uses: actions/setup-go@v3
        name: Setup go
        with:
          go-version: '1.19'
          cache: true
      - run: go version

      - name: run tests
        run: |
          go test ./... -cover -coverprofile=coverage.out -v

  bump-version:
    name: Bump Version
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
      - name: Bump version && push tag
        uses: hennejg/github-tag-action@v4.3.1
        with:
          github_token: ${{ secrets.GH_PAT }}
          release_branches: 'main'